### ISSUE TITLE
MELPA package

### ISSUE THREAD

**Issue by CestDiego** [syohex/emacs-fontawesome#1]
Hello, this package is great, have you considered putting it up on MELPA?

**Comment by syohex** [comment]
> have you considered putting it up on MELPA?

No, however if you think so,  please sent PR to MELPA in place of me.

**Comment by CestDiego** [comment]
Is that even possible? ok will do.

**Comment by syohex** [comment]
Thanks.

**Comment by CestDiego** [comment]
In the meanwhile, could you re-run the make script to have the symbols updated? :) I think the melpa package should only include the data, not the makefile.

**Comment by syohex** [comment]
Done

**Comment by CestDiego** [comment]
I think one issue with this is that you should rename the repo to the same name as the package. Or the other way round. According to this https://github.com/CestDiego/melpa#contributing-new-recipes

**Comment by CestDiego** [comment]
oh nvm I made it work :)

**Comment by CestDiego** [comment]
This was merged at MELPA, https://github.com/milkypostman/melpa/commit/7b55cbb8e452d702e581a05dc910571fecbf97a3
