### ISSUE TITLE
Feature request: Working Helmless

### ISSUE THREAD

**Issue by technician77** [syohex/emacs-fontawesome#10]
Would it be much of work to write the package in a way that it doesn't require helm? I know many people like helm, but I don't and by far I'm not alone. Would it be possible to use ivy alternatively?

Kind regards,
technician77

**Comment by syohex** [comment]
I have added `counsel-fontawesome` and remove helm dependency from package header and it's optional requirement now.

**Comment by technician77** [comment]
Wow, thanks a lot. Will try asap.

Some people like me just can't warm up themselves with large frameworks like helm. For them this is really great news.

Kind regards,
technician77
