### ISSUE TITLE
Unicode boxes when using counsel-fontawesome

### ISSUE THREAD

**Issue by technician77** [syohex/emacs-fontawesome#12]
Hello Syohex,

quite likely that it's just me being stupid, but when I use counsel-fontawesome I get unicodeboxes on the selected entry in the list. The other unselected entries show fine. When inserting the selected entry it's also a unicode box. I use Source-Code-Pro as my default font. I have no special unicode configuration except `(prefer-coding-system 'utf-8-auto)`. Do I need to do some configuration you know of to make it work as intended? Emacs is `GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-11-15` on Win7.

![image](https://cloud.githubusercontent.com/assets/18722291/23361057/f9e80b20-fcee-11e6-8982-43773c32e0a3.png)

Kind regards,
technician77

**Comment by syohex** [comment]
> Do I need to do some configuration you know of to make it work as intended? 

Sorry I don't know. However I cannot reproduce this issue on macOS, so it seems that this is windows issue.

**Comment by technician77** [comment]
![image](https://cloud.githubusercontent.com/assets/18722291/23583161/947ce9ca-013c-11e7-97c3-79187c2413f5.png)

Fixed using this:
`(set-fontset-font t 'unicode "FontAwesome" nil 'prepend)`

Uh, I'm really fond of font awesome but could "Fond awesome" be a typo? See screenshots

**Comment by syohex** [comment]
Ah sorry it's typo. I have fixed.
