### ISSUE TITLE
Support for custom icons

### ISSUE THREAD

**Issue by sagis-tikal** [syohex/emacs-fontawesome#15]
I think it would be best to have a file which:

- The user will be able to use as a custom list of icons - provided its formatted correctly.
  - The users will be able to add their own sets of icons.
  - The users won't need to wait for a new revision of this project for every change on the main fontawesome branch.

- P.S. it has to not get overwritten on upgrade.

Cheers, 
Sagi

**Comment by syohex** [comment]
Sorry for late reply.
This package is no longer maintained. If you want to add new feature, please fork repository and use it.
