### ISSUE TITLE
incorrect character width

### ISSUE THREAD

**Issue by blaenk** [syohex/emacs-fontawesome#4]
I'm not sure how fonts work in emacs and I think this is most likely nothing to do with this package, but in case you know of a possible solution, I'm wondering if you know how to correct the fact that emacs thinks some characters in this font only take up one column when they clearly take up two.

See [this question](https://emacs.stackexchange.com/questions/14420/how-can-i-fix-incorrect-character-width) for more information.

![column width](http://i.imgur.com/QpEDGHi.png)

**Comment by syohex** [comment]
"\xf0c2" is ambiguous characters. Width of ambiguous characters is changed by context. So I suppose it is not wrong that `(string-width "\xf0c2")` returns 1. You can set their font width to 2, please evaluate this [code](https://gist.github.com/atton-/9478540#file-east-asian-ambiguous-el)

See also
- http://unicode.org/reports/tr11/#Ambiguous

**Comment by blaenk** [comment]
Woah thanks a ton, this was bugging me for a long while and I just now got the idea to ask here. If you make an answer on the stackexchange post I'll be glad to mark it as the answer, but in any case, thanks a ton!
