### ISSUE TITLE
Any way to update it to 4.7 ?

### ISSUE THREAD

**Issue by jwintz** [syohex/emacs-fontawesome#7]
Latest version is 4.7, I do not know if there are breaks in backward compatibility (i.e. if individual font codes have changed and which are not bound to the same name anymore).

Great package anyways ! Make my emacs pretty ;-)

**Comment by syohex** [comment]
Sorry late response. I have updated https://github.com/syohex/emacs-fontawesome/pull/9

**Comment by jwintz** [comment]
Great thanks !
