### ISSUE TITLE
helm-fontawesome buffer encoding

### ISSUE THREAD

**Issue by jwintz** [syohex/emacs-fontawesome#8]
Hello,

For some reasons I can't explain, fontawesome for emacs works great on my mac laptop, but not on my mac desktop, I however have the exact same setup since it is under version control (brew packages and emacs version are identical, just as `~/.bashrc` and `~/.bash_profile`).

Also, my emacs config contains:

```
(prefer-coding-system 'utf-8)

(setq coding-system-for-read 'utf-8)
(setq coding-system-for-write 'utf-8)
```

Any ideas why I have this rendering issues ?

Thanks !

**Comment by syohex** [comment]
- What is `not working` ? Could you show screenshots on both environment ?
- Did you install fonts ?
- Do you use same version Emacs on both environment ? Color font is disabled on macOS since Emacs 25

**Comment by jwintz** [comment]
I'm running Emacs 26.0.50.1 on Sierra, on both systems and fonts are installed. They show correctly in `helm-fontawesome` buffer, but not once inserted. However it doesn't affect all glyphs. As an example, `git` and `dashboard` render just fine, while `tag` and `align-left` don't.

![screen shot 2016-12-19 at 15 46 55](https://cloud.githubusercontent.com/assets/3277054/21317100/fb1a6942-c603-11e6-8838-3c0a759bbed0.png)

The former should be rendered in the first line, and the latter as the first character of the modeline.

And here it show it shows when everything is in place:

<img width="724" alt="screen shot 2016-12-19 at 17 06 03" src="https://cloud.githubusercontent.com/assets/3277054/21319421/88878f5e-c60d-11e6-9969-79eb014e5c6a.png">

Anyway, I'll try to figure it out myself, thanks for the support and the excellent packages !

**Comment by jwintz** [comment]
Fixed. When appending to buffer from emacs-lisp, use:

```emacs-lisp
(propertize "" 'face '(:family "FontAwesome"))
```

instead of just

```
"" 
```
